apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-demo-alvaro
  namespace: cluster-elastic-demo
spec:
  version: 8.9.0
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.store.allow_mmap: false
      node.roles: [ master ]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 2Gi  
  - name: datahot-nodes
    count: 2
    config:
      node.roles: [ data_hot, ingest ]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 4Gi
              cpu: 1
            limits:
              memory: 4Gi   
  - name: datawarm-nodes
    count: 2
    config:
      node.roles: [ data_warm, ingest ]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 3Gi
              cpu: 1
            limits:
              memory: 3Gi      
  - name: coord-node
    count: 1
    config:
      node.roles: [ ]
      node.store.allow_mmap: false
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            requests:
              memory: 512Mi
              cpu: 1
            limits:
              memory: 512Mi  
  http:
    tls:
      selfSignedCertificate:
        disabled: true
     
