apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: elastic-demo-alvaro
  namespace: cluster-elastic-demo
spec:
  version: 8.9.0
  nodeSets:
  - name: master-nodes
    count: 3
    config:
      node.store.allow_mmap: false
      node.roles: [ master ]
    podTemplate:
      metadata:
        labels:
          env: dev
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - elastic-pool
        tolerations:
        - key: elastic-only
          operator: Equal
          value: "true"
          effect: NoSchedule
  - name: datahot-nodes
    count: 1
    config:
      node.roles: [ data_hot, ingest ]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          env: dev
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - hot-nodes-1
        tolerations:
        - key: elastic-hot-data
          operator: Equal
          value: "true"
          effect: NoSchedule
  - name: datawarm-nodes
    count: 1
    config:
      node.roles: [ data_warm, ingest ]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          env: dev
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - elastic-pool
        tolerations:
        - key: elastic-only
          operator: Equal
          value: "true"
          effect: NoSchedule
  - name: coord-node
    count: 1
    config:
      node.roles: [ ]
      node.store.allow_mmap: false
    podTemplate:
      metadata:
        labels:
          env: dev
      spec:
        initContainers:
        - name: sysctl
          securityContext:
            privileged: true
          command: ['sh', '-c', 'sysctl -w vm.max_map_count=262144']
        affinity:
          nodeAffinity:
            requiredDuringSchedulingIgnoredDuringExecution:
              nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - elastic-pool
        tolerations:
        - key: elastic-only
          operator: Equal
          value: "true"
          effect: NoSchedule
  http:
    tls:
      selfSignedCertificate:
        disabled: true
     
