apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elastic-cluster-alvaro
spec:
  version: 8.9.0
  count: 1
  elasticsearchRef:
    name: elastic-cluster-alvaro
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 2  
  http:
    tls:
      selfSignedCertificate:
        disabled: true