apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: cluster-elastic-demo
spec:
  version: 8.9.0
  count: 1
  elasticsearchRef:
    name: elastic-demo-alvaro
  podTemplate:
    metadata:
      labels:
        env: dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: cloud.google.com/gke-nodepool
                  operator: In
                  values:
                  - general-stack-pool
        tolerations:
        - key: elk-only
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=2048"
          
