apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: cluster-elastic-demo
spec:
  version: 8.9.0
  monitoring:
    metrics:
      elasticsearchRefs:
      - name: elastic-demo-alvaro
   logs:
      elasticsearchRefs:
      - name: elastic-demo-alvaro
  count: 1
  elasticsearchRef:
    name: elastic-demo-alvaro
  http:
    service:
      spec:
      # Type of service to deploy for Kibana.
      # This deploys a load balancer in a cloud service provider, where supported.
      # 
        type: LoadBalancer  
  podTemplate:
    metadata:
      labels:
        env: dev
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - general-stack-pool
      tolerations:
      - key: elk-only
        operator: Equal
        value: "true"
        effect: NoSchedule
      
